
# -*- coding: utf-8 -*-
"""Final Assignment (Best Team) .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p11659_r3c6xekiI7hIKmhQz8wBso-9K

# Loading in Packages and Data
"""

import dash
import dash_core_components as dcc
import dash_bootstrap_components as dbc
import dash_html_components as html
import plotly.express as px
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

app = dash.Dash(__name__)
server = app.server

df = pd.read_csv('https://storage.googleapis.com/hk1159/COVID_data.csv')


"""### Data Cleaning

"""

import pandas as pd
import numpy as np
import plotly.graph_objs as go
import plotly.express as px


cols_dd = ["GDP_pc", "indicator_val","ln_GDP_pc"]
# we need to add this to select which trace 
# is going to be visible
visible = np.array(cols_dd)

# define traces and buttons at once
traces = []
buttons = []
for value in cols_dd:
    traces.append(go.Choropleth(
       locations=df['code'], # Spatial coordinates
        z=df[value].astype(float), # Data to be color-coded
        colorbar_title=value,
        visible= True if value==cols_dd[0] else False))

    buttons.append(dict(label=value,
                        method="update",
                        args=[{"visible":list(visible==value)},
                              {"title":f"<b>{value}</b>"}]))

updatemenus = [{"active":0,
                "buttons":buttons,
               }]


# Show figure
fig = go.Figure(data=traces,
                layout=dict(updatemenus=updatemenus))
# This is in order to get the first title displayed correctly
first_title = cols_dd[0]
#fig.update_layout(title=f"<b>{first_title}</b>",title_x=0.5)
fig.update_layout(
    title_text = 'Data Collection Regions',
)

"""# Pie chart of World Surveys"""
import plotly.express as px
new_df=df.groupby('region')['region'].count().rename_axis('Customer').reset_index(name='request')
df_tips = px.data.tips()
pie2 = px.pie(df_tips, values=new_df.request, names=new_df.Customer, color_discrete_sequence=px.colors.sequential.RdBu)
pie2.update_layout(
    title_text='Surveys during Covid-19 around the World'
)
"""# Sunburst Chart of World surveys for top 3 surveyed country"""

import plotly.express as px
import pandas as pd
import numpy as np


df2 = df[df["region"].isin(['Sub-Saharan Africa', 'Latin America & Caribbean', 'East Asia & Pacific'])]
df2 = df2[df2["indicator_topic"].isin(['Food Security','Demographic','Labor','Education','Preventive behaviors','Income','Vaccination','Knowledge','Safety Nets','Health'])]


fig2 = px.sunburst(
    data_frame=df2,
    path=["region", 'indicator_topic', "indicator_description"],
    color="indicator_val",
    color_discrete_sequence=px.colors.qualitative.Pastel,
    title='COVID-19 Effect in Different Regions of the World'

)

fig2.update_traces(textinfo='label+percent entry')
#fig2.update_layout(margin=dict(t=0, l=0, r=0, b=0))

# First bar chart code 

from pandas.core.frame import DataFrame

Region_Counts =df['region'].value_counts()
RegionForPlot = DataFrame({'Region':Region_Counts.index, 'Count':Region_Counts.values})
RegionCountBar = px.bar(RegionForPlot, x='Count', y='Region', orientation='h',title= "Volume Surveyed by Region")

# Stacked Bar Chart Code

import plotly.express as px

groupeddata = DataFrame({'count' : df.groupby(['region','urban_rural'] ).size()}).reset_index()
groupeddata = DataFrame(groupeddata)
groupeddata  = groupeddata[groupeddata["region"].isin(['Sub-Saharan Africa', 'Latin America & Caribbean', 'East Asia & Pacific'])]
Stacked_Rural = px.bar(groupeddata , x='region', y='count', color='urban_rural', title="Urban and Rural Divide in the top 3 Regions")

# GDP Box Plot
df3 = df[df["region"].isin(['Sub-Saharan Africa', 'Latin America & Caribbean', 'East Asia & Pacific'])]
boxplot3regions = px.box(df3, y="GDP_pc", x="region", color = "industry", title = "Top 3 Surveyed Regions by GDP and Industry")


### Raduan Plots & Data  Cleaning
df.drop(['indicator_description','survey_producer','survey_link','last_updated'], axis=1, inplace=True)
df_mnyrconv = df.dropna(subset=['month', 'year'])
df_mnyrconv['month'] = df_mnyrconv['month'].astype(int)
df_mnyrconv['Data Collection Date'] = (df_mnyrconv['month'].astype(str).fillna('') + df_mnyrconv['year'].astype(str).fillna(''))
df_mnyrconv['Data_Collection_Date'] = pd.to_datetime(df_mnyrconv['Data Collection Date'].astype(str), format='%m%Y')
dtvc=df_mnyrconv['Data_Collection_Date'].value_counts()
dtvc=df['Data_Collection_Date'] = pd.to_datetime(df_mnyrconv['Data Collection Date'].astype(str), format='%m%Y')

dftf = px.data.stocks()
fig_datetime = px.histogram(df_mnyrconv, x="Data_Collection_Date",title="Data Collection TimeFrame")
fig_datetime.update_layout(bargap=0.2)

## Second Graph
df.dropna(subset=["indicator_topic"], inplace=True)
dvac=df[df.indicator_topic == 'Vaccination']
dvacnot=dvac[dvac.indicator_display.isin(['Not wanting or unsure about vaccination for other reasons  *','Not wanting or unsure about vaccination because they already had COVID-19 *','Not wanting or unsure about vaccination because do not think it will work *','Not wanting or unsure about vaccination because they are worried about side effects *','Not wanting or unsure about vaccination because low risk of contracting COVID-19 *','Not wanting or unsure about vaccination because they don\'t trust vaccines in general *','Not wanting or unsure about vaccination because it\'s against religion *','Not wanting or unsure about vaccination because they are worried about getting COVID-19 at the health facility *','Not wanting or unsure about vaccination because the health facility is hard to get to *','Not wanting or unsure about vaccination because it takes to long to get vaccinated / don\'t have time *'])]
dvacyes=dvac[dvac.indicator_display.isin(['Have been vaccinated for COVID-19 (% of respondents)','Plan to take COVID-19 vaccine (% of respondents)','Plan to take COVID-19 vaccine when it is available (% of respondents)'])]
dnv=notvacinc=dvacnot['income_group'].value_counts()
dk=notvacregn=dvacnot['region'].value_counts()
dl=vacinc=dvacyes['income_group'].value_counts()
dw=vacregn=dvacyes['region'].value_counts()
dtw1=vacregn1=dvacyes['country'].value_counts()
dtw2=vacregn2=dvacnot['country'].value_counts()

import plotly.graph_objects as go

income = ['High income', 'Upper middle income', 'Lower middle income', 'Low income']

figincomevacin = go.Figure()
figincomevacin.add_trace(go.Bar(x=income,
                y=[220, 2168, 1209, 1490],
                name='Not Interested in Vaccine',
                marker_color='rgb(120, 130, 255)'
                ))
figincomevacin.add_trace(go.Bar(x=income,
                y=[122, 718, 338, 296],
                name='Interested in Vaccine',
                marker_color='rgb(0, 160, 0)'
                ))

figincomevacin.update_layout(
    title='People\'s Interest in Vaccine Depending on Their Income Group',
    xaxis_tickfont_size=14,
    yaxis=dict(
        title='Number of Responders',
        titlefont_size=16,
        tickfont_size=14,
    ),
    legend=dict(
        x=0.85,
        y=1.0,
        bgcolor='rgba(255, 255, 255, 0)',
        bordercolor='rgba(255, 255, 255, 0)'
    ),
    barmode='group',
    bargap=0.15, # gap between bars of adjacent location coordinates.
    bargroupgap=0.1 # gap between bars of the same location coordinate.
)

## Third Graph

import plotly.graph_objects as go

region = ['Latin America & Caribbean', 'Sub-Saharan Africa ', 'East Asia & Pacific', 'Europe & Central Asia', 'Middle East & North Africa']

figincomevacnot = go.Figure()
figincomevacnot.add_trace(go.Bar(x=region,
                y=[1700, 1599, 820, 690, 278],
                name='Not Interested in Vaccine',
                marker_color='rgb(255, 0, 0)'
                ))
figincomevacnot.add_trace(go.Bar(x=region,
                y=[778, 309, 189, 162, 36],
                name='Interested in Vaccine',
                marker_color='rgb(26, 118, 255)'
                ))

figincomevacnot.update_layout(
    title='People\'s Interest in Vaccine Depending on Their Region',
    xaxis_tickfont_size=14,
    yaxis=dict(
        title='Number of Responders',
        titlefont_size=16,
        tickfont_size=14,
    ),
    legend=dict(
        x=0.85,
        y=1.0,
        bgcolor='rgba(255, 255, 255, 0)',
        bordercolor='rgba(255, 255, 255, 0)'
    ),
    barmode='group',
    bargap=0.19, # gap between bars of adjacent location coordinates.
    bargroupgap=0.1 # gap between bars of the same location coordinate.
)

## Graph 4 

import plotly.graph_objects as go

labels = ['National','Urban','Rural']
values = dvacnot['urban_rural'].value_counts()

# Use `hole` to create a donut-like pie chart
figdounats = go.Figure(data=[go.Pie(labels=labels, values=values, hole=.5)])
figdounats.update_layout(
    title_text="Urban-Rural responder's who are not interested in COVID-19 vaccine or they think it's harmful for them",

)

## Graph 5 

import plotly.graph_objects as go

years = ["Latin America & Caribbean", "Sub-Saharan Africa", "East Asia & Pacific", "Europe & Central Asia","Middle East & North Africa"]

figcopi = go.Figure()
figcopi.add_trace(go.Bar(x=years, y=[-324, 485, 265, 245, 24],
                base=[0, -485, -265, -245, -24],
                marker_color='crimson',
                name='Copi_sold'))
figcopi.add_trace(go.Bar(x=years, y=[648, 903, 580, 322, 32],
                base=0,
                marker_color='lightslategrey',
                name='Copi used and reduced'
                ))
figcopi.update_layout(
    title_text="Effect of COVID-19 in Good Consumption in Different Region",
    yaxis=dict(
        title='Number of Responders',
        titlefont_size=16,
        tickfont_size=14,
    ),

)



## Graph 6 
import plotly.express as px
figboxin = px.box(dvacyes, y="GDP_pc", points="all")
figboxin.update_layout(title_text="GDP Per Capita of the country where people are interested in vaccine") 

figboxnot = px.box(dvacnot, y="GDP_pc", points="all")
figboxnot.update_layout(title_text="GDP Per Capita of the country where people are not interested in vaccine") 

# Fairus Plots 

house_hold_covid=pd.read_csv('https://storage.googleapis.com/hj9407/covid_household.csv')
house_hold_covid.columns = house_hold_covid.columns.str.replace(' ', '_')
house_hold_covid.columns = house_hold_covid.columns.str.replace('.', '_')
house_hold_covid.columns = house_hold_covid.columns.str.capitalize()
house_hold_covid['Month'].fillna('5',inplace=True)
house_hold_covid.drop(['Code','Region','Lending_category','Measure_type','Weight_type','Footnote','Survey_producer','Survey_link','Last_updated','Source','Fcs','Ln_gdp_pc'],axis=1,inplace=True)
job_change=house_hold_covid[(house_hold_covid['Indicator_topic']=='Labor')&(house_hold_covid['Indicator']=='Labo_chang')]
segments=[-1,30,40,np.inf]
labels=['Below 30%','31%-40%','Over 40%']
Percent_respondent=pd.cut(job_change.Indicator_val,segments,labels=labels)
job_change['Percent_respondent']=Percent_respondent
job_change['Time']= job_change['Month'].astype('str')+ '-' +  job_change['Year'].astype('str')

## First Graph

new_df=job_change.groupby('Income_group')['Indicator_val'].mean().rename_axis('income_group').reset_index(name='indicator_value')

fig_job_bar = px.bar(new_df, x='income_group', y='indicator_value', orientation='v')
fig_job_bar.update_layout(
    height=600,
    title_text='Job Changing Tendency of People within Different Income Group around the World'
)

## Second Graph


fig_job_year = px.bar(job_change, x="Income_group", y="Indicator_val", color="Income_group",
  animation_frame="Year", animation_group="Country", range_y=[0,45])
fig_job_year.update_layout(
    height=600,
    title_text='Job Changing Tendency During Pandemic Time'
)

## Third Graph


fig_job_bubble = px.scatter(job_change.query("Year==2020"), x="Gdp_pc", y="Indicator_val",
	         size="Sample_subset", color="Region_code",
                 hover_name="Country", log_x=True, size_max=60)
fig_job_bubble.update_layout(
    height=600,
    title_text='Bubble Chart of Job Changing Tendency around Different Region of the World'
)

## Fourth Graph

fig_bubble_year=px.scatter(job_change, x="Gdp_pc", y="Indicator_val", animation_frame="Year", animation_group="Country",
           size="Sample_subset", color="Region_code", hover_name="Country",
           log_x=True, size_max=55, range_x=[1000,100000], range_y=[0,45])
fig_bubble_year.update_layout(
    height=600,
    title_text='Bubble Chart of Job Changing Tendency during Pandemic Time'
)

## Graph 5 

fig_world_tree = px.treemap(job_change, path=[px.Constant("world"), 'Region_code', 'Country'], values='Sample_subset',
                  color='Indicator_val', hover_data=['Income_group'],
                  color_continuous_scale='RdBu',
                  color_continuous_midpoint=np.average(job_change['Indicator_val'], weights=job_change['Sample_subset']))
fig_world_tree.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig_world_tree.update_layout(
    height=600,
    title_text='World Tree Map'
)

# Graph 6 

fig_scatter_job = px.scatter(job_change, x="Income_group", y="Sample_subset", color="Indicator_val",
                 title="Scatter Plot of Job Changing Tendency among Different Income Group")

# Raw Stats for beginning cards
uniquecountries = len(df['country'].unique())
uniqueregions = len(df['region'].unique())
GDP_avg = df['GDP_pc'].mean()
cards  = dbc.CardGroup(
    [
      dbc.Card(
          dbc.CardBody(
               [
                     html.H4("Distinct Number of Countries", id="card-title"),
                     html.H2(uniquecountries, id="card-value")
               ]
                     )
             ),     

      dbc.Card(
          dbc.CardBody(
               [
                       html.H4("Number of Regions Represented", id="card-title2"),
                       html.H2(uniqueregions, id="card-value2")
               ]
                    )
               ),
       dbc.Card(
                      dbc.CardBody(
                 [
                                    html.H4("Average of GDP Pc", id="card-title3"),
                                    html.H2(GDP_avg, id="card-value3")
                  ]
                            )
                ),
       
    ]
)



app.layout = html.Div(
    #header piece
     children=[
         html.Div(
             children=[
                     html.H1(children="Data Analysis for COVID-19 Effects on Households and Regions", className="header-title"),

                        html.P(  children="by Paul Merica, Asia Dahmes, Fairus Tanzim and MD Raduanul H. Chowdhury ",

                            className="header-description"

                                ),

                ],

            className="header",

        ),
    html.Div(children='''
       To start, we wanted to look at which countries were surveyed and the rough estimate of GDP for each country.
    ''', style={'textAlign': 'center'}),
    dcc.Graph(
        id='example-graph',
        figure=fig
    ),
    html.Div(children='''
       Now that we have a nice visual of the countries and their respective GDP's. We wanted to show some summary statistics on the number of countries represented, regions represented and their average GDP.
    ''', style={'textAlign': 'center'}),
    html.Div([
                 dbc.Row([
                            dbc.Col([cards])
                        ]),
    ]),
    html.Div(children='''
         Then we wanted to see what regions were sampled the highest and some other statisitics related to region.
    ''', style={'textAlign': 'center'}),

    dbc.Row([
            #Boxplot
            dbc.Col([
                 dcc.Graph(
                 id='example-graph3',
                   figure=pie2
                     ),
                    ]), 
            
            dbc.Col([
                #Step change cuts 
                        dcc.Graph(
                      id='Pie Chart 2',
                      figure=fig2
                      ),
                    ]),
                ]),
    html.Div(children='''
       The majority of the surveys were collected from Sub Saharan Africa, Latin America and East Asia & Pacific region where people got affected by Covid-19 in different sectors. In the Sub-Saharan Africa 40% of surveys took place where large portion of respondents expressed their interest in preventive behaviors and few portion of respondents revealed their assistance during Covid-19. 
       At the same time, large number of respondents expressed their awareness about Covid-19 and these large respondents planned to take vaccine when it becomes available.  

    ''', style={'textAlign': 'center'}),
    dcc.Graph(
        id='example-graph5',
        figure=RegionCountBar
    ),
    html.Div(children='''
       Through our pie chart and total count estimate. We see here that the top 3 regions sampled are Latin America, Africa and East Asia. 
       Now that we have the top 3 most sampled regions, we wanted to look at if there was any Differences in Rural/Urban divide between the regions.
    ''', style={'textAlign': 'center'}),
    dcc.Graph(
        id='example-graph4',
        figure=Stacked_Rural
    ),
     html.Div(children='''
       It appears here that there might not be a huge difference in the rural urban divide. Which made us want to look back at the GDP of each region and the industries in them to see if other any differences.
    ''', style={'textAlign': 'center'}),
        dcc.Graph(
        id='example-graph6',
        figure=boxplot3regions
    ),
     html.Div(children='''
            From here it looks like Sub Saharan has the lowest GDP, while East Asia comes in second and Latin America has the highest GDP of these 3 regions we are focusing on.
            It does not appear that any industries are significantly different, although some do have different means. From all this we have learned the highest sampled regions were Latin America, Sub Saharan Africa and East Asia. Also that out of these 3, Latin America had the highest GDP_pc.
            Another takeaway is that these regions are relatively low GDP on a global scale as countries like the United States aren't in this dataset.             
    ''', style={'textAlign': 'center'}),

    html.Div(children='''
       Now we start looking at data collection time frame and vaccinations concerns of the responders.
    ''', style={'textAlign': 'center','color': 'blue', 'fontSize': 30,'marginBottom': 50, 'marginTop': 25}),
       dcc.Graph(
        id='example-graph7',
        figure=fig_datetime
    ),
    html.Div(children='''
       Most of the data was collected in the countries when they were affected by the first wave of COVID-19 (as per most of the countries).
       because, from the above graph we can see maximum data was collected between May, 2020 to August, 2020. Then again a huge chunk of data was collected in June, 2021.
    ''', style={'textAlign': 'center'}),
    dcc.Graph(
        id='example-graph8',
        figure=figincomevacin
    ),
    html.Div(children='''
       People's interest in vaccine depending on their income group. Where UMI = Upper Middle Income, LI = Low Income, LMI = Low Middle Income, HI = High Income. 
       It turns out that low income group's ratio of not interested in vaccine/interested in vaccine, is highest (4.39) and this ratio is lowest in high income group (1.88).
        The survey also incorporated a lot of people from upper middle income group.As predicted,
         low-income groups people are more hesitant to get vaccinated for wide range of reasons but high income group people are more interested.
    ''', style={'textAlign': 'center'}),
 dcc.Graph(
        id='example-graph9',
        figure=figincomevacnot
    ),
    html.Div(children='''
     It turns out that Middle East & North Africa region's ratio of not interested in vaccine/interested in vaccine, is highest (7.72) and this ratio is lowest in Latin America & Caribbean (2.18). 
     This is beacuse the financial situation of the countries of these region. 
     Latin America and Caribbean are poorer compare to Middle Eastern region.
    ''', style={'textAlign': 'center'}),
     dcc.Graph(
        id='example-graph13',
        figure=figdounats
    ),
    html.Div(children='''
       According to Figure from before, the people who are not interested in getting vaccine are mostly from National area (44.5%), with 32.4% from Urban area and 23.1% from Rural area.
    ''', style={'textAlign': 'center'}),
    dcc.Graph(
        id='example-graph10',
        figure=figcopi
    ),
    html.Div(children='''
      Provides a clear idea of how comparatively richer region Middle East & North Africa's people day-to-day living wasn't hampered extensively in comparison with Sub-Saharan Africa (poorer region).
       In Sub-Saharan Africa, a lot of people had to sell their assets to ensure basic living. 
    ''', style={'textAlign': 'center'}),
       dcc.Graph(
        id='figboxin',
        figure=figboxin
    ),
       dcc.Graph(
        id='figboxnot',
        figure=figboxnot
    ),
    html.Div(children='''
 Represents the ln GDP of people from different region who want to get vaccinated and don't want to get vaccinated  respectively.
  These plots also imply that richer countries people are most likely to get vaccinated compared to the poor.

    ''', style={'textAlign': 'center'}),
     html.Div(children='''
 We were also interested in job changing tendency during the pandemic. This section explores that part of the pandemic.

    ''',style={'textAlign': 'center','color': 'blue', 'fontSize': 30,'marginBottom': 50, 'marginTop': 25}),
       dcc.Graph(
        id='fig_job_bar',
        figure= fig_job_bar
    ),
       dcc.Graph(
        id='fig_job_year',
        figure=fig_job_year
    ),
        html.Div(children='''
 On average, people from high income group has changed their job duing Covid-19 pandemic time. 
 People from High income and Upper Middle Income group took opportunity to change job during these time whereas percentage of job changing tendency among Low Income group is lower. 
 Another analysis revealed that people from each income group changed their job more during 2nd year of pandemic than 1st year.   

    ''', style={'textAlign': 'center'}),
         dcc.Graph(
        id='fig_job_bubble',
        figure= fig_job_bubble
    ),
       dcc.Graph(
        id='fig_bubble_year',
        figure=fig_bubble_year
    ),
   html.Div(children='''
 During surveys of job changing tendency among different GDP_pc countries, large number of surveys took place in East Asia & Pacific whose GDP-pc stands near 8K-9k. 
 Percentage of respondent among Sub Saharan Africa changed their job lower than other region whose GDP-pc falls below 5K. 
 On the other hand, analysis showed that large portion of respondent from Latin America region changed their job during 2nd year of pandemic than 1st year.


    ''', style={'textAlign': 'center'}),
    dcc.Graph(
        id='fig_bubble_tree',
        figure=fig_world_tree 
    ),
 html.Div(children='''
    World Tree Map has been analysed to show the job changing tendency from different regions which revealed that more surveys took place in East Asia and Pacific and few surveys took place in Middle east and North Africa.
     Respondents from Ethiopia and Sierra Leone didnt change their job whereas more respondents from Brazil, Belize and Nicaragua changed their job during Pandemic.
    ''', style={'textAlign': 'center'}),
     dcc.Graph(
        id='fig_scatter_job ',
        figure=fig_scatter_job 
    ),
 html.Div(children='''
Most of the surveys for people's job changing took place among Lower Middle Income group and less surveys occured among High Income Group. Although from the less surveys, High income group people responded that they changed their job during pandemic than other income group people. Large portion of Low income and Lower Middle Income group people responded that they didnt change their job during Pandemic. 
It can also be assumed that people of High Income Group are not comfortable of revealing their job changing information whereas Low Income or Lower Middle Income group are flexible about it.  
    ''', style={'textAlign': 'center'}),
    html.Div(
             children=[
                     html.H1(children="Conclusion", className="header-title"),

                        html.P(  children="In conclusion, we found that East Asia, Latin America and Subsaharan Africa were the heaviest sampled regions. We also found that richer countries in GDP were more likely to get vaccinated than poorer countries. Then along this economic vein, we looked at job changing tendency among nations, and that people from higher income groups changed their jobs more than lower income groups during the pandemic.",

                            className="header-description"

                                ),

                ],

            className="header",

        )
 
])


if __name__ == '__main__':
 app.run_server(debug=True, port=8080)